/*
Refresh before expiry (issue #91): recompute an entry once its remaining ttl drops
below a threshold, so the stored value is replaced while it is still live and no
caller ever waits for the recompute or reads an expired entry.

This is the companion to `examples/stale_while_revalidate.rs`. That one handles the
entry that has ALREADY expired, by serving it stale while a refresh runs. This one
moves the refresh earlier, so the expired state is never reached.

Three primitives do the work:

1. `cache_peek_expires_at(&key) -> (Option<V>, Option<Instant>)` (alias
   `peek_expires_at`) returns the stored value TOGETHER with the instant it expires
   at, and (being the peek variant) removes nothing, updates no recency, and counts
   no hit or miss. The deadline is an `Instant` and not a remaining `Duration`
   because a `Duration` cannot distinguish "never expires" from "already expired":
   `(Some(v), None)` is a value with no deadline at all, handled explicitly below.

2. `cache_expires_at(&key) -> (bool, Option<Instant>)` (alias `expires_at`) is the
   same side-effect-free lookup without the value: the `bool` is presence and the
   `Option<Instant>` is the same deadline. It carries no `V: Clone` bound and never
   touches the stored value, so it also works on a value type that is not `Clone`.

   Which of the two to call is decided by what the caller does next. A read that
   SERVES the cached value needs the value anyway, so it uses the peek and takes the
   deadline along with it (sections 1 to 4). A read that only decides "should I
   refresh?" uses the value-free form, so it does not clone the whole value on the
   hot path only to drop the clone (`sync_remaining`, `sync_needs_refresh`,
   `async_needs_refresh`, `sharded_needs_refresh`, `opaque_deadline` below). On a
   large value that clone is the most expensive thing in the read.

   The presence flag is not redundant with the deadline. Absent and present-with-no-
   deadline call for OPPOSITE actions - fetch the key cold versus do nothing - and a
   bare `Option<Instant>` collapses them into one `None`, which is why the policy
   below takes the pair.

3. `{fn}_prime_cache(args)` recomputes and stores under the same key. It runs the
   function body BEFORE taking the cache write lock, so a refresh never blocks the
   readers being served the current value.

The policy is one comparison:

    let remaining = deadline.saturating_duration_since(Instant::now());
    if remaining < THRESHOLD { /* refresh in the background */ }

THRESHOLD must exceed the recompute time, or the refresh cannot land before the
deadline and the policy degrades to stale-while-revalidate.

Spawning is left to the caller on purpose: `cached` has no runtime dependency, so it
cannot pick tokio or smol on your behalf. That also means you decide the policy -
whether to rate-limit refreshes, drop them under load, or run them on a dedicated pool.

The cache static generated by the macro carries the cached function's own visibility,
so all three primitives are reachable from the call site. Its shape depends on the
macro and on whether the function is async, so the sections below spell out each one:

    sync  #[cached]            LazyLock<parking_lot::RwLock<Store>>   .read()
    async #[cached]            LazyLock<async_lock::RwLock<Store>>    .read().await
    async #[concurrent_cached] OnceCell<Store>                        .get() (no guard)

Two macro forms this recipe does NOT apply to:

    in_impl   `#[cached(in_impl)]`, `#[concurrent_cached(in_impl)]` and
              `#[once(in_impl)]` generate no `{fn}_prime_cache` companion: the cache
              static is function-local and cannot be shared with a prime sibling, so
              there is nothing to refresh with.
    #[once]   keeps its own expiry timer around one shared value rather than storing
              it in a cache implementing `CacheExpiry`, so there is nothing to read.

Section 0 is the policy itself; sections 1 to 3 cover the read side per store shape;
section 4 covers `expires = true`, where the deadline comes from the value rather
than from a store-wide ttl; section 5 collapses concurrent refreshes onto one
caller with `cached::claim::ClaimRegistry`; section 6 asserts the property this
example exists for: across a window spanning the threshold, every read is served
a live value, no read waits for the recompute, and the value is replaced exactly
once.

The timing assertions compare against NO_WAIT, a budget well under COMPUTE, so they
separate "served from the cache" from "waited for the recompute" with room to spare
for scheduling jitter.

Run:
    cargo run --example refresh_before_expiry --features "proc_macro,time_stores,async"
*/

use std::sync::LazyLock;
use std::sync::atomic::{AtomicBool, AtomicUsize, Ordering};

use cached::claim::ClaimRegistry;
use cached::macros::{cached, concurrent_cached};
use cached::time::{Duration, Instant};
use cached::{CacheExpiry, ConcurrentCacheExpiry, Expires};

/// Recompute cost of every cached body below.
const COMPUTE: Duration = Duration::from_millis(200);

/// Refresh once less than this much ttl is left. Every function below uses
/// `ttl_secs = 2`, so this fires in the second half of the entry's life. It must
/// exceed `COMPUTE`, or the refresh cannot land before the deadline.
const THRESHOLD: Duration = Duration::from_secs(1);

/// Budget for a read that must not wait for the recompute. A read that did wait
/// takes at least `COMPUTE` (200ms), while a peek plus a spawn costs microseconds
/// even under load (measured consistently at 0ms locally with 8 concurrent runs of
/// this whole example oversubscribed on a 4-core box, plus CPU-burning background
/// processes on every core). 180ms keeps a real 200ms+ wait clearly on the other
/// side while giving more headroom against scheduler jitter than a tighter budget
/// would on a slower or more heavily shared CI runner than that.
const NO_WAIT: Duration = Duration::from_millis(180);

/// Counts real executions of a function body, so the output distinguishes a served
/// value from a recompute.
static COMPUTES: AtomicUsize = AtomicUsize::new(0);

/// Counts reads that found an entry past its deadline. The whole point of the
/// threshold is to keep this at zero; `main` asserts it.
static EXPIRED_READS: AtomicUsize = AtomicUsize::new(0);

fn compute_count() -> usize {
    COMPUTES.load(Ordering::SeqCst)
}

fn expired_reads() -> usize {
    EXPIRED_READS.load(Ordering::SeqCst)
}

// ============================================================================
// 0. The threshold policy
//
// The only place the deadline is interpreted, shared by every section below.
// Every `None` case is a real state, not an error path: an absent key has nothing
// to refresh, no deadline means nothing to refresh ahead of, and a zero remaining
// means the entry already expired.
//
// The argument is the `(bool, Option<Instant>)` pair `cache_expires_at` returns, so
// a caller that only needs the decision writes `needs_refresh(cache.expires_at(&k))`
// with no destructuring and no clone of the value. Taking the pair also keeps the
// absent case in ONE place: with a bare `Option<Instant>` an absent key and a
// never-expiring entry both arrive as `None`, so every call site would have to
// establish presence separately before trusting the answer.
// ============================================================================

fn needs_refresh(entry: (bool, Option<Instant>)) -> bool {
    let (present, expires_at) = entry;

    if !present {
        // Nothing is stored under this key. The fix is a cold fetch, which is the
        // caller's miss branch, not a refresh: there is no live value to keep alive
        // and `{fn}_prime_cache` would recompute behind a caller that is about to
        // block on the same body anyway.
        return false;
    }

    let Some(deadline) = expires_at else {
        // Present with no deadline. On a ttl store that means the ttl was disabled
        // at insert time, so the entry never expires and there is nothing to
        // refresh ahead of. This is the case a remaining-`Duration` API could not
        // express - it would have to report either zero or some sentinel, and zero
        // means the exact opposite. On an `expires = true` store it means something
        // weaker: the value type does not report a deadline at all, which says
        // nothing about liveness. Section 4 covers that.
        return false;
    };

    let remaining = deadline.saturating_duration_since(Instant::now());

    if remaining.is_zero() {
        // Past the deadline. The refresh did not land in time, so this caller is
        // about to be served a stale value, which is the situation
        // `examples/stale_while_revalidate.rs` covers. Raising THRESHOLD (or
        // making the body cheaper) is what keeps this branch cold.
        EXPIRED_READS.fetch_add(1, Ordering::SeqCst);
    }

    remaining < THRESHOLD
}

// ============================================================================
// 1. Synchronous `#[cached]`
//
// The static is a `parking_lot::RwLock`, so the read guard is taken without
// `.await`. Bind the peek in its own scope so the guard is dropped before the
// call below. This is not a throughput tweak: calling the cached function or
// `{fn}_prime_cache` takes the write lock on that same `RwLock`, `parking_lot`'s
// `RwLock` is not reentrant, and the thread then deadlocks permanently, with no
// panic and no output.
// ============================================================================

#[cached(ttl_secs = 2, key = "String", convert = r#"{ id.to_string() }"#)]
fn sync_lookup(id: &str) -> String {
    let n = COMPUTES.fetch_add(1, Ordering::SeqCst) + 1;
    std::thread::sleep(COMPUTE);
    format!("{id}-v{n}")
}

fn sync_lookup_refreshed(id: &str) -> String {
    let (value, expires_at) = {
        let cache = SYNC_LOOKUP.read();
        // The key must be built exactly as the `convert` block builds it. If the two
        // ever drift you silently peek a different entry, so keep them side by side.
        cache.peek_expires_at(&id.to_string())
    };

    match value {
        Some(v) => {
            // `(true, ...)`: the peek above already established presence, so the
            // policy's absent branch cannot be reached from here. This path serves
            // the value, so it needs the peek; the reads below that only decide do
            // not.
            if needs_refresh((true, expires_at)) {
                let owned = id.to_string();
                std::thread::spawn(move || {
                    sync_lookup_prime_cache(&owned);
                });
            }
            // Returned whether or not a refresh was spawned: the value is still
            // live, so this caller never waits.
            v
        }
        // Nothing cached yet. There is no value to serve, so this call waits.
        None => sync_lookup(id),
    }
}

/// How much ttl is left, used by `main` for a printout. The value-free read: the
/// deadline is all this needs, so `cache_expires_at` reads it out of the same
/// non-promoting lookup without cloning the stored `String` only to drop it. Like
/// the peek it is side-effect free, so reading it for a printout cannot perturb
/// what the section measures.
fn sync_remaining(id: &str) -> Option<Duration> {
    let cache = SYNC_LOOKUP.read();
    let (_present, expires_at) = cache.expires_at(&id.to_string());
    expires_at.map(|deadline| deadline.saturating_duration_since(Instant::now()))
}

/// The threshold policy driven straight off the value-free read: no value is
/// cloned, and the absent key (`(false, None)`) is answered by the policy itself.
fn sync_needs_refresh(id: &str) -> bool {
    let cache = SYNC_LOOKUP.read();
    needs_refresh(cache.expires_at(&id.to_string()))
}

// ============================================================================
// 2. Asynchronous `#[cached]`
//
// Identical shape, except the static is an `async_lock::RwLock`, so the read is
// `.read().await`. The scope around the peek carries the same hard requirement:
// `async_lock`'s `RwLock` is not reentrant either, so awaiting the cached
// function or `{fn}_prime_cache` while the read guard is alive parks the task on
// a write lock it can never get - a permanent hang with no panic and no output.
// Holding the guard across an await point would also serialize every reader
// against the refresh, but that is the lesser of the two problems.
// ============================================================================

#[cached(ttl_secs = 2, key = "String", convert = r#"{ id.to_string() }"#)]
async fn async_lookup(id: &str) -> String {
    let n = COMPUTES.fetch_add(1, Ordering::SeqCst) + 1;
    tokio::time::sleep(COMPUTE).await;
    format!("{id}-v{n}")
}

async fn async_lookup_refreshed(id: &str) -> String {
    let (value, expires_at) = {
        let cache = ASYNC_LOOKUP.read().await;
        cache.peek_expires_at(&id.to_string())
    };

    match value {
        Some(v) => {
            if needs_refresh((true, expires_at)) {
                let owned = id.to_string();
                tokio::spawn(async move {
                    async_lookup_prime_cache(&owned).await;
                });
            }
            v
        }
        None => async_lookup(id).await,
    }
}

/// The value-free counterpart on the async store: the read guard is `.read().await`,
/// the read itself is the same `expires_at` and clones nothing.
async fn async_needs_refresh(id: &str) -> bool {
    let cache = ASYNC_LOOKUP.read().await;
    needs_refresh(cache.expires_at(&id.to_string()))
}

// ============================================================================
// 3. Asynchronous `#[concurrent_cached]`
//
// The sharded stores synchronize internally, so the static is the store itself
// behind a `OnceCell` (initialized by the first call) with no outer lock: reach
// through the cell and peek directly. The trait is `ConcurrentCacheExpiry`,
// which takes `&K` rather than a `Borrow<Q>`.
// ============================================================================

#[concurrent_cached(ttl_secs = 2, key = "String", convert = r#"{ id.to_string() }"#)]
async fn sharded_lookup(id: &str) -> String {
    let n = COMPUTES.fetch_add(1, Ordering::SeqCst) + 1;
    tokio::time::sleep(COMPUTE).await;
    format!("{id}-v{n}")
}

async fn sharded_lookup_refreshed(id: &str) -> String {
    // `get()` is `None` only before the first call has initialized the cell, which
    // is indistinguishable from a miss for our purposes.
    let peeked = SHARDED_LOOKUP
        .get()
        .map(|cache| cache.peek_expires_at(&id.to_string()));

    match peeked {
        Some((Some(v), expires_at)) => {
            if needs_refresh((true, expires_at)) {
                let owned = id.to_string();
                tokio::spawn(async move {
                    sharded_lookup_prime_cache(&owned).await;
                });
            }
            v
        }
        _ => sharded_lookup(id).await,
    }
}

/// The value-free read on the sharded store, through `ConcurrentCacheExpiry`. An
/// uninitialized cell reports the same `(false, None)` a miss does, which is exactly
/// what the policy already treats as "fetch cold, do not refresh". No guard and no
/// `.await`: the sharded store synchronizes internally.
fn sharded_needs_refresh(id: &str) -> bool {
    let entry = SHARDED_LOOKUP
        .get()
        .map_or((false, None), |cache| cache.expires_at(&id.to_string()));
    needs_refresh(entry)
}

// ============================================================================
// 4. `expires = true`: the deadline comes from the value
//
// On the ttl stores the deadline is the store's own clock reading, so it is
// always known. On the `Expires`-based stores (`expires = true`, giving an
// `ExpiringCache` or, with `max_size`, an `ExpiringLruCache`) both reads report
// whatever `Expires::expires_at()` returns, and that method is DEFAULTED to
// `None`. Every `Expires` impl shipped in this repo (see
// `examples/expires_per_key.rs`) implements only `is_expired`, and on such a type
// the reads return `(Some(v), None)` / `(true, None)` for live and expired entries
// alike, so the threshold policy above is a no-op: `needs_refresh((true, None))` is
// always false and no refresh is ever spawned. Override `expires_at` to opt in, as
// `Token` does here. `is_expired` stays the authority on liveness either way - the
// deadline is advisory and the store never reconciles the two.
//
// Note that the presence flag is NOT advisory in the same way: `(true, None)` means
// present with an unknown deadline, and it is still distinct from the `(false, None)`
// of an absent key. That is why the policy can act on presence but not on `None`.
// ============================================================================

/// Reports both: `is_expired` for the store, `expires_at` for this recipe.
#[derive(Clone)]
struct Token {
    data: String,
    deadline: Instant,
}

impl Expires for Token {
    fn is_expired(&self) -> bool {
        Instant::now() >= self.deadline
    }

    /// Without this override every peek of a `Token` reports no deadline and
    /// nothing below fires.
    fn expires_at(&self) -> Option<Instant> {
        Some(self.deadline)
    }
}

/// The far more common shape: `is_expired` only. `main` asserts that the policy
/// cannot see a deadline on it, live or expired.
#[derive(Clone)]
struct OpaqueToken {
    data: String,
    deadline: Instant,
}

impl Expires for OpaqueToken {
    fn is_expired(&self) -> bool {
        Instant::now() >= self.deadline
    }
}

#[cached(expires = true, key = "String", convert = r#"{ id.to_string() }"#)]
fn token_lookup(id: &str) -> Token {
    let n = COMPUTES.fetch_add(1, Ordering::SeqCst) + 1;
    std::thread::sleep(COMPUTE);
    Token {
        data: format!("{id}-v{n}"),
        deadline: Instant::now() + Duration::from_secs(2),
    }
}

/// Lifetime of an `OpaqueToken`, short enough for `main` to peek it on both sides
/// of its own deadline.
const OPAQUE_TTL: Duration = Duration::from_millis(300);

#[cached(expires = true, key = "String", convert = r#"{ id.to_string() }"#)]
fn opaque_lookup(id: &str) -> OpaqueToken {
    // Counted (and folded into `data`) so a real read that recomputes this entry is
    // distinguishable from one that reused the stored value, the same way every other
    // cached body in this file is.
    let n = COMPUTES.fetch_add(1, Ordering::SeqCst) + 1;
    OpaqueToken {
        data: format!("{id}-opaque-v{n}"),
        deadline: Instant::now() + OPAQUE_TTL,
    }
}

fn token_lookup_refreshed(id: &str) -> Token {
    let (value, expires_at) = {
        let cache = TOKEN_LOOKUP.read();
        cache.peek_expires_at(&id.to_string())
    };

    match value {
        Some(v) => {
            if needs_refresh((true, expires_at)) {
                let owned = id.to_string();
                std::thread::spawn(move || {
                    token_lookup_prime_cache(&owned);
                });
            }
            v
        }
        None => token_lookup(id),
    }
}

/// The advisory deadline an `OpaqueToken` entry reports, which is `None` whatever
/// its state. `(bool, Option<Instant>)` is `cache_expires_at`'s own return shape, so
/// this is the read itself rather than a peek with the value thrown away - and the
/// presence flag comes from the store instead of from `value.is_some()`.
fn opaque_deadline(id: &str) -> (bool, Option<Instant>) {
    let cache = OPAQUE_LOOKUP.read();
    cache.expires_at(&id.to_string())
}

// ============================================================================
// 5. Collapsing concurrent refreshes
//
// Every caller that reads the entry between the threshold and the landing of the
// new value sees the same short remaining ttl, so each spawns its own refresh:
// N readers cause N recomputes. Track the keys already being refreshed and let
// the first caller win.
//
// This covers the refresh only. The cold path (`None => async_lookup(id)`) still
// lets N concurrent first callers all run the body; `sync_writes = "by_key"` is
// what deduplicates that, and section 5 of `examples/stale_while_revalidate.rs`
// composes the two.
//
// `cached::claim::ClaimRegistry` is that set of keys. `claim` hands the first
// caller a `Claim` and every later caller `None`, until that claim is dropped.
//
// The release comes from the claim's `Drop` rather than from a `release(id)`
// statement at the end of the spawned task, because such a statement is skipped
// when the refresh body panics or the task is aborted. The key would then stay
// claimed for the life of the process, and since the peek deliberately never
// removes an expired entry, it would be served past its deadline forever with no
// caller able to recompute it: strictly worse than the stale-while-revalidate
// fallback. `main` asserts the panicking and the cancelled path.
//
// `ClaimRegistry::new` is not `const`, so a `static` registry needs `LazyLock`.
// The registry is also cheap to clone, so it can live in a struct field instead.
// ============================================================================

static REFRESHING: LazyLock<ClaimRegistry<String>> = LazyLock::new(ClaimRegistry::new);

async fn async_lookup_refreshed_deduped(id: &str) -> String {
    let (value, expires_at) = {
        let cache = ASYNC_LOOKUP.read().await;
        cache.peek_expires_at(&id.to_string())
    };

    match value {
        Some(v) => {
            // `claim` runs only past the threshold, so the uncontended path never
            // touches the registry's mutex.
            if needs_refresh((true, expires_at))
                && let Some(claim) = REFRESHING.claim(id.to_string())
            {
                tokio::spawn(async move {
                    // `claim` is dropped when this task ends, on its own completion,
                    // on an unwind out of the refresh, or on cancellation, and the
                    // key is released in all three cases. Borrowing the key out of
                    // the guard is what keeps it alive for exactly the refresh: the
                    // guard cannot be dropped early without a borrow error.
                    async_lookup_prime_cache(claim.key()).await;
                });
            }
            v
        }
        None => async_lookup(id).await,
    }
}

/// Set to make the next `flaky_lookup` body panic, so `main` can drive a refresh
/// that fails partway through.
static PANIC_NEXT_REFRESH: AtomicBool = AtomicBool::new(false);

#[cached(ttl_secs = 2, key = "String", convert = r#"{ id.to_string() }"#)]
async fn flaky_lookup(id: &str) -> String {
    let n = COMPUTES.fetch_add(1, Ordering::SeqCst) + 1;
    assert!(
        !PANIC_NEXT_REFRESH.swap(false, Ordering::SeqCst),
        "simulated refresh failure"
    );
    format!("{id}-v{n}")
}

/// The spawn shape above, reduced to the claim and the refresh, so `main` can
/// await the outcome. Returns `None` when a refresh is already in flight.
fn spawn_refresh(id: &str) -> Option<tokio::task::JoinHandle<()>> {
    let claim = REFRESHING.claim(id.to_string())?;
    Some(tokio::spawn(async move {
        flaky_lookup_prime_cache(claim.key()).await;
    }))
}

/// A body slow enough that `main` can reliably abort its task mid-flight, to prove the
/// claim also releases when the task is CANCELLED rather than unwound by a panic.
/// `claim` lives inside the spawned future's own captured state, so `JoinHandle::abort`
/// dropping that future in place runs the `Claim`'s `Drop` exactly the same as an unwind
/// or a normal return does - there is no separate "cancellation" case in the guard itself,
/// only in how the future stops running.
#[cached(ttl_secs = 2, key = "String", convert = r#"{ id.to_string() }"#)]
async fn stuck_lookup(id: &str) -> String {
    let n = COMPUTES.fetch_add(1, Ordering::SeqCst) + 1;
    tokio::time::sleep(Duration::from_secs(5)).await;
    format!("{id}-v{n}")
}

/// The spawn shape above, over `stuck_lookup`, so `main` can abort the handle mid-flight.
fn spawn_stuck_refresh(id: &str) -> Option<tokio::task::JoinHandle<()>> {
    let claim = REFRESHING.claim(id.to_string())?;
    Some(tokio::spawn(async move {
        stuck_lookup_prime_cache(claim.key()).await;
    }))
}

// ============================================================================
// 6. Never expired, never blocked
//
// The property that separates this from stale-while-revalidate. Read one key
// across a window that spans the threshold and check three things: the value was
// replaced (so the refresh really ran), no read was served an entry past its
// deadline, and no read took anywhere near the recompute time.
// ============================================================================

/// Reads `id` every `step` for `window`, returning the distinct values observed in
/// order plus the slowest single read.
async fn poll(id: &str, window: Duration, step: Duration) -> (Vec<String>, Duration) {
    let until = Instant::now() + window;
    let mut observed: Vec<String> = Vec::new();
    let mut slowest = Duration::ZERO;

    while Instant::now() < until {
        let started = Instant::now();
        let value = async_lookup_refreshed_deduped(id).await;
        slowest = slowest.max(started.elapsed());
        if observed.last() != Some(&value) {
            observed.push(value);
        }
        tokio::time::sleep(step).await;
    }

    (observed, slowest)
}

#[tokio::main]
async fn main() {
    // --- 0. the policy ------------------------------------------------------
    // The `(true, None)` case, which none of the ttl-backed reads below can
    // produce: an entry with no deadline never expires, so it never refreshes.
    println!("no deadline -> refresh: {}", needs_refresh((true, None)));
    assert!(
        !needs_refresh((true, None)),
        "an entry with no deadline must never be refreshed"
    );

    // `(false, None)`: absent. Same `None` deadline, opposite meaning - the caller's
    // miss branch fetches it cold, and the policy must not turn that into a refresh
    // of an entry that does not exist. This is the distinction a bare
    // `Option<Instant>` argument could not carry.
    println!("absent      -> refresh: {}", needs_refresh((false, None)));
    assert!(
        !needs_refresh((false, None)),
        "an absent key must be fetched cold, never refreshed"
    );

    // `(true, Some(future))` on both sides of the threshold. Kept in the future so
    // the expired-read counter below stays untouched by the policy demo itself.
    let above = Instant::now() + THRESHOLD + Duration::from_secs(1);
    let below = Instant::now() + THRESHOLD / 2;
    println!(
        "above/below the {}ms threshold -> refresh: {} / {}",
        THRESHOLD.as_millis(),
        needs_refresh((true, Some(above))),
        needs_refresh((true, Some(below)))
    );
    assert!(!needs_refresh((true, Some(above))));
    assert!(needs_refresh((true, Some(below))));

    // --- 1. synchronous -----------------------------------------------------
    println!("\nsync `#[cached]`");
    // The same `(false, None)` read against the real store, before anything is
    // cached under "a".
    println!("  absent key -> refresh: {}", sync_needs_refresh("a"));
    assert!(
        !sync_needs_refresh("a"),
        "a key that is not cached yet must not be refreshed"
    );

    let before = compute_count();
    let first = sync_lookup_refreshed("a");
    println!(
        "  cold miss  -> {first} ({} compute)",
        compute_count() - before
    );

    let early = sync_lookup_refreshed("a");
    println!(
        "  early read -> {early}, {}ms left, over the {}ms threshold, no refresh",
        sync_remaining("a").unwrap_or_default().as_millis(),
        THRESHOLD.as_millis()
    );
    assert_eq!(early, first);
    assert_eq!(
        compute_count() - before,
        1,
        "a read above the threshold must not refresh"
    );
    assert!(
        !sync_needs_refresh("a"),
        "the value-free read must agree: still above the threshold"
    );

    std::thread::sleep(Duration::from_millis(1_300));
    let started = Instant::now();
    let at_threshold = sync_lookup_refreshed("a");
    // Captured before anything else runs: the budget below is for the read alone,
    // not for the read plus the printout.
    let took = started.elapsed();
    let remaining = sync_remaining("a").unwrap_or_default();
    println!(
        "  threshold  -> {at_threshold} returned in {}ms with {}ms still live, refresh spawned",
        took.as_millis(),
        remaining.as_millis()
    );
    assert_eq!(at_threshold, first, "the entry is refreshed, not evicted");
    assert!(!remaining.is_zero(), "the entry must still be live");
    assert!(took < NO_WAIT, "the caller must not wait (took {took:?})");
    assert!(
        sync_needs_refresh("a"),
        "the value-free read must agree: now under the threshold"
    );

    std::thread::sleep(Duration::from_millis(400));
    let refreshed = sync_lookup_refreshed("a");
    println!(
        "  after bg   -> {refreshed} ({} computes), replaced before expiring",
        compute_count() - before
    );
    assert_ne!(refreshed, first, "the refresh must have replaced the value");
    assert_eq!(compute_count() - before, 2);

    // --- 2. asynchronous ----------------------------------------------------
    println!("\nasync `#[cached]`");
    assert!(
        !async_needs_refresh("b").await,
        "a key that is not cached yet must not be refreshed"
    );

    let before = compute_count();
    let first = async_lookup_refreshed("b").await;
    println!("  cold miss  -> {first}");

    tokio::time::sleep(Duration::from_millis(1_300)).await;
    let started = Instant::now();
    let at_threshold = async_lookup_refreshed("b").await;
    let took = started.elapsed();
    println!(
        "  threshold  -> {at_threshold} returned in {}ms, refresh spawned",
        took.as_millis()
    );
    assert_eq!(at_threshold, first);
    assert!(took < NO_WAIT, "the caller must not wait (took {took:?})");
    assert!(
        async_needs_refresh("b").await,
        "the value-free read must agree: now under the threshold"
    );

    tokio::time::sleep(Duration::from_millis(400)).await;
    let refreshed = async_lookup_refreshed("b").await;
    println!(
        "  after bg   -> {refreshed} ({} computes)",
        compute_count() - before
    );
    assert_ne!(refreshed, first);
    assert_eq!(compute_count() - before, 2);

    // --- 3. sharded ---------------------------------------------------------
    println!("\nasync `#[concurrent_cached]`");
    // Read before the first call, so the `OnceCell` is still uninitialized: the same
    // `(false, None)` a miss reports, and the same answer.
    assert!(
        !sharded_needs_refresh("c"),
        "an uninitialized cache cell must not be refreshed"
    );

    let before = compute_count();
    let first = sharded_lookup_refreshed("c").await;
    println!("  cold miss  -> {first}");

    tokio::time::sleep(Duration::from_millis(1_300)).await;
    let started = Instant::now();
    let at_threshold = sharded_lookup_refreshed("c").await;
    let took = started.elapsed();
    println!(
        "  threshold  -> {at_threshold} returned in {}ms, refresh spawned",
        took.as_millis()
    );
    assert_eq!(at_threshold, first);
    assert!(took < NO_WAIT, "the caller must not wait (took {took:?})");
    assert!(
        sharded_needs_refresh("c"),
        "the value-free read must agree: now under the threshold"
    );

    tokio::time::sleep(Duration::from_millis(400)).await;
    let refreshed = sharded_lookup_refreshed("c").await;
    println!(
        "  after bg   -> {refreshed} ({} computes)",
        compute_count() - before
    );
    assert_ne!(refreshed, first);
    assert_eq!(compute_count() - before, 2);

    // --- 4. `expires = true` ------------------------------------------------
    println!("\nsync `#[cached(expires = true)]`");
    let before = compute_count();
    let first = token_lookup_refreshed("d");
    println!("  cold miss  -> {}", first.data);

    std::thread::sleep(Duration::from_millis(1_300));
    let started = Instant::now();
    let at_threshold = token_lookup_refreshed("d");
    let took = started.elapsed();
    println!(
        "  threshold  -> {} returned in {}ms, refresh spawned",
        at_threshold.data,
        took.as_millis()
    );
    assert_eq!(at_threshold.data, first.data);
    assert!(took < NO_WAIT, "the caller must not wait (took {took:?})");

    std::thread::sleep(Duration::from_millis(400));
    let refreshed = token_lookup_refreshed("d");
    println!(
        "  after bg   -> {} ({} computes), replaced before expiring",
        refreshed.data,
        compute_count() - before
    );
    assert_ne!(refreshed.data, first.data);
    assert_eq!(compute_count() - before, 2);

    // The caveat, on the value type that implements only `is_expired`. Read here
    // through `cache_expires_at`, whose `(present, deadline)` return is exactly what
    // this caveat is about: the presence flag is authoritative, the deadline is not.
    let opaque = opaque_lookup("d");
    let entry = opaque_deadline("d");
    let (present, deadline) = entry;
    println!(
        "  is_expired-only {} -> present {present}, deadline {deadline:?}, refresh {}",
        opaque.data,
        needs_refresh(entry)
    );
    assert!(present);
    assert_eq!(
        deadline, None,
        "a value type that does not override expires_at reports no deadline"
    );
    assert!(
        !needs_refresh(entry),
        "the threshold policy is a no-op on an is_expired-only value type"
    );

    std::thread::sleep(OPAQUE_TTL + Duration::from_millis(50));
    let (present, deadline) = opaque_deadline("d");
    println!("  the same entry, now expired -> present {present}, deadline {deadline:?}");
    assert!(present, "the read must not remove the expired entry");
    assert_eq!(
        deadline, None,
        "None does not mean live: the entry is expired and still reports no deadline"
    );

    // The reads above only ever touch `OPAQUE_LOOKUP` through `cache_expires_at`,
    // which never removes or replaces anything - so nothing yet has exercised what an
    // ACTUAL read (the cached function itself) does with this same expired entry. The
    // store's lazy sweep is keyed off `is_expired`, not off the advisory (and here
    // absent) deadline, so a real call must still recompute and replace it.
    let before = compute_count();
    let read_after_expiry = opaque_lookup("d");
    println!(
        "  a real read of the expired entry -> {} ({} compute)",
        read_after_expiry.data,
        compute_count() - before
    );
    assert_ne!(
        read_after_expiry.data, opaque.data,
        "a real read of an expired is_expired-only entry must recompute, not reuse the stale value"
    );
    assert_eq!(
        compute_count() - before,
        1,
        "the real read must recompute exactly once"
    );
    let (present, deadline) = opaque_deadline("d");
    println!("  read again after the real read -> present {present}, deadline {deadline:?}");
    assert!(present, "the freshly-recomputed entry is live");
    assert_eq!(
        deadline, None,
        "the fresh entry still does not override expires_at either"
    );

    // --- 5. deduplicated refresh --------------------------------------------
    println!("\ncollapsing concurrent refreshes");
    let cold = async_lookup_refreshed_deduped("e").await;
    tokio::time::sleep(Duration::from_millis(1_300)).await;

    let before = compute_count();
    let started = Instant::now();
    let mut handles = Vec::new();
    for _ in 0..8 {
        handles.push(tokio::spawn(async {
            async_lookup_refreshed_deduped("e").await
        }));
    }
    let mut served = Vec::new();
    for handle in handles {
        served.push(handle.await.expect("reader task panicked"));
    }
    let elapsed = started.elapsed();
    println!(
        "  8 concurrent readers past the threshold -> served {} in {}ms",
        served[0],
        elapsed.as_millis()
    );
    assert!(
        served.iter().all(|v| *v == cold),
        "all readers see the live value"
    );
    assert!(
        elapsed < NO_WAIT,
        "no reader may wait for the refresh (took {elapsed:?})"
    );

    tokio::time::sleep(Duration::from_millis(400)).await;
    let refreshes = compute_count() - before;
    println!(
        "  -> {refreshes} recompute(s), next read {}",
        async_lookup_refreshed_deduped("e").await
    );
    assert_eq!(
        refreshes, 1,
        "the in-flight guard must collapse the refreshes to one"
    );

    // The claim releases from `Drop`, so a refresh that panics still releases its
    // key. Were it released by a statement at the end of the task instead, `g` would
    // stay claimed for the life of the process and could never be refreshed again.
    let cold = flaky_lookup("g").await;
    PANIC_NEXT_REFRESH.store(true, Ordering::SeqCst);
    let previous_hook = std::panic::take_hook();
    std::panic::set_hook(Box::new(|_| {})); // the panic below is deliberate
    let failing = spawn_refresh("g").expect("the first caller must claim the refresh");
    let outcome = failing.await;
    std::panic::set_hook(previous_hook);
    assert!(outcome.is_err(), "the refresh task must have panicked");

    let retry = spawn_refresh("g").expect("a panicking refresh must not wedge the key");
    retry.await.expect("the retry must not panic");
    let stored = {
        let cache = FLAKY_LOOKUP.read().await;
        cache.peek_expires_at(&"g".to_string()).0
    };
    println!("  a panicking refresh released its claim, retry stored {stored:?}");
    assert!(
        stored.is_some(),
        "the retried refresh must have stored a value"
    );
    assert_ne!(
        stored.as_deref(),
        Some(cold.as_str()),
        "the retry must have replaced the value the panicking refresh failed to"
    );

    // The other way a spawned task can stop running without reaching its own end: the
    // caller drops or aborts the `JoinHandle` instead of the body panicking. The guard
    // must release the claim here too - it is released by drop, and a cancelled task's
    // future is dropped just like any other, whether or not it ever panicked.
    let _ = stuck_lookup("h").await; // seed an entry so the claim below is meaningful
    let stuck = spawn_stuck_refresh("h").expect("the first caller must claim the refresh");
    // Give the task a chance to actually start running (and be parked inside its 5s
    // sleep) before aborting it - aborting a task the runtime never polled would prove
    // nothing about releasing a claim held mid-execution.
    tokio::time::sleep(Duration::from_millis(50)).await;
    stuck.abort();
    let cancelled = stuck.await;
    assert!(
        cancelled.as_ref().is_err_and(|e| e.is_cancelled()),
        "the task must have been cancelled, not merely finished on its own: {cancelled:?}"
    );
    let retry_claim = REFRESHING.claim("h".to_string());
    println!(
        "  an aborted refresh released its claim: retry claim succeeded {}",
        retry_claim.is_some()
    );
    assert!(
        retry_claim.is_some(),
        "an aborted refresh must release its claim, not wedge the key forever"
    );
    drop(retry_claim);
    assert!(
        !REFRESHING.is_claimed("h"),
        "the registry must drain the key once the retry claim is dropped too"
    );

    // --- 6. never expired, never blocked ------------------------------------
    println!("\nnever expired, never blocked");
    let before = compute_count();
    let expired_before = expired_reads();
    let first = async_lookup_refreshed_deduped("f").await;

    // 1.6s of reads over a 2s ttl: the threshold trips at 1.0s and the refresh
    // lands ~0.2s later, so the window covers the handover in both directions.
    let (observed, slowest) = poll(
        "f",
        Duration::from_millis(1_600),
        Duration::from_millis(100),
    )
    .await;
    println!("  reads across the threshold -> {observed:?}");
    println!(
        "  slowest read {}ms, recompute {}ms, {} expired read(s)",
        slowest.as_millis(),
        COMPUTE.as_millis(),
        expired_reads() - expired_before
    );
    assert_eq!(observed.len(), 2, "the value must be replaced mid-window");
    assert_eq!(
        observed[0], first,
        "reads before the handover see the old value"
    );
    assert_ne!(observed[1], first, "reads after it see the refreshed value");
    assert_eq!(
        compute_count() - before,
        2,
        "one cold compute plus exactly one background refresh"
    );
    assert!(
        slowest < NO_WAIT,
        "no read may wait for the recompute (slowest {slowest:?})"
    );

    // The point of issue #91: the entry was replaced without any caller ever
    // reaching the expired state that stale-while-revalidate exists to absorb.
    assert_eq!(
        expired_reads(),
        0,
        "no read in this example may observe an expired entry"
    );

    println!("\nrefresh-before-expiry ok");
}
