/*
Refresh before expiry (issue #91): recompute an entry once its remaining ttl drops
below a threshold, so the stored value is replaced while it is still live and no
caller ever waits for the recompute or reads an expired entry.

This is the companion to `examples/stale_while_revalidate.rs`. That one handles the
entry that has ALREADY expired, by serving it stale while a refresh runs. This one
moves the refresh earlier, so the expired state is never reached.

Two primitives do the work:

1. `cache_peek_expires_at(&key) -> (Option<V>, Option<Instant>)` (alias
   `peek_expires_at`) returns the stored value TOGETHER with the instant it expires
   at, and (being the peek variant) removes nothing, updates no recency, and counts
   no hit or miss. The deadline is an `Instant` and not a remaining `Duration`
   because a `Duration` cannot distinguish "never expires" from "already expired":
   `(Some(v), None)` is a value with no deadline at all, handled explicitly below.

2. `{fn}_prime_cache(args)` recomputes and stores under the same key. It runs the
   function body BEFORE taking the cache write lock, so a refresh never blocks the
   readers being served the current value.

The policy is one comparison:

    let remaining = deadline.saturating_duration_since(Instant::now());
    if remaining < THRESHOLD { /* refresh in the background */ }

THRESHOLD must exceed the recompute time, or the refresh cannot land before the
deadline and the policy degrades to stale-while-revalidate.

Spawning is left to the caller on purpose: `cached` has no runtime dependency, so it
cannot pick tokio or smol on your behalf. That also means you decide the policy -
whether to rate-limit refreshes, drop them under load, or run them on a dedicated pool.

The cache static generated by the macro carries the cached function's own visibility,
so both primitives are reachable from the call site. Its shape depends on the macro
and on whether the function is async, so the sections below spell out each one:

    sync  #[cached]            LazyLock<parking_lot::RwLock<Store>>   .read()
    async #[cached]            LazyLock<async_lock::RwLock<Store>>    .read().await
    async #[concurrent_cached] OnceCell<Store>                        .get() (no guard)

Section 0 is the policy itself; sections 1 to 3 cover the read side per shape;
section 4 collapses concurrent refreshes onto one caller; section 5 asserts the
property this example exists for: across a window spanning the threshold, every read
is served a live value, no read waits for the recompute, and the value is replaced
exactly once.

Run:
    cargo run --example refresh_before_expiry --features "proc_macro,time_stores,async"
*/

use std::collections::HashSet;
use std::sync::Mutex;
use std::sync::atomic::{AtomicUsize, Ordering};

use cached::macros::{cached, concurrent_cached};
use cached::time::{Duration, Instant};
use cached::{CacheExpiry, ConcurrentCacheExpiry};

/// Recompute cost of every cached body below.
const COMPUTE: Duration = Duration::from_millis(200);

/// Refresh once less than this much ttl is left. Every function below uses
/// `ttl_secs = 2`, so this fires in the second half of the entry's life. It must
/// exceed `COMPUTE`, or the refresh cannot land before the deadline.
const THRESHOLD: Duration = Duration::from_secs(1);

/// Counts real executions of a function body, so the output distinguishes a served
/// value from a recompute.
static COMPUTES: AtomicUsize = AtomicUsize::new(0);

/// Counts reads that found an entry past its deadline. The whole point of the
/// threshold is to keep this at zero; `main` asserts it.
static EXPIRED_READS: AtomicUsize = AtomicUsize::new(0);

fn compute_count() -> usize {
    COMPUTES.load(Ordering::SeqCst)
}

fn expired_reads() -> usize {
    EXPIRED_READS.load(Ordering::SeqCst)
}

// ============================================================================
// 0. The threshold policy
//
// The only place the deadline is interpreted, shared by every section below.
// Both `None` cases are real states, not error paths: no deadline means the
// entry never expires, and a zero remaining means it already expired.
// ============================================================================

fn needs_refresh(expires_at: Option<Instant>) -> bool {
    let Some(deadline) = expires_at else {
        // Present with no deadline (ttl disabled at insert time): the entry never
        // expires, so there is nothing to refresh ahead of. This is the case a
        // remaining-`Duration` API could not express - it would have to report
        // either zero or some sentinel, and zero means the exact opposite.
        return false;
    };

    let remaining = deadline.saturating_duration_since(Instant::now());

    if remaining.is_zero() {
        // Past the deadline. The refresh did not land in time, so this caller is
        // about to be served a stale value, which is the situation
        // `examples/stale_while_revalidate.rs` covers. Raising THRESHOLD (or
        // making the body cheaper) is what keeps this branch cold.
        EXPIRED_READS.fetch_add(1, Ordering::SeqCst);
    }

    remaining < THRESHOLD
}

// ============================================================================
// 1. Synchronous `#[cached]`
//
// The static is a `parking_lot::RwLock`, so the read guard is taken without
// `.await`. Bind the peek in its own scope so the guard drops before the spawn:
// the refresh will want the write lock.
// ============================================================================

#[cached(ttl_secs = 2, key = "String", convert = r#"{ id.to_string() }"#)]
fn sync_lookup(id: &str) -> String {
    let n = COMPUTES.fetch_add(1, Ordering::SeqCst) + 1;
    std::thread::sleep(COMPUTE);
    format!("{id}-v{n}")
}

fn sync_lookup_refreshed(id: &str) -> String {
    let (value, expires_at) = {
        let cache = SYNC_LOOKUP.read();
        // The key must be built exactly as the `convert` block builds it. If the two
        // ever drift you silently peek a different entry, so keep them side by side.
        cache.peek_expires_at(&id.to_string())
    };

    match value {
        Some(v) => {
            if needs_refresh(expires_at) {
                let owned = id.to_string();
                std::thread::spawn(move || {
                    sync_lookup_prime_cache(&owned);
                });
            }
            // Returned whether or not a refresh was spawned: the value is still
            // live, so this caller never waits.
            v
        }
        // Nothing cached yet. There is no value to serve, so this call waits.
        None => sync_lookup(id),
    }
}

/// The same peek, used by `main` to print how much ttl is left. It is side-effect
/// free, so reading it for a printout cannot perturb what the section measures.
fn sync_remaining(id: &str) -> Option<Duration> {
    let cache = SYNC_LOOKUP.read();
    let (_, expires_at) = cache.peek_expires_at(&id.to_string());
    expires_at.map(|deadline| deadline.saturating_duration_since(Instant::now()))
}

// ============================================================================
// 2. Asynchronous `#[cached]`
//
// Identical shape, except the static is an `async_lock::RwLock`, so the read is
// `.read().await`. The scope around the peek matters more here: holding the
// guard across an `.await` would serialize every reader against the refresh.
// ============================================================================

#[cached(ttl_secs = 2, key = "String", convert = r#"{ id.to_string() }"#)]
async fn async_lookup(id: &str) -> String {
    let n = COMPUTES.fetch_add(1, Ordering::SeqCst) + 1;
    tokio::time::sleep(COMPUTE).await;
    format!("{id}-v{n}")
}

async fn async_lookup_refreshed(id: &str) -> String {
    let (value, expires_at) = {
        let cache = ASYNC_LOOKUP.read().await;
        cache.peek_expires_at(&id.to_string())
    };

    match value {
        Some(v) => {
            if needs_refresh(expires_at) {
                let owned = id.to_string();
                tokio::spawn(async move {
                    async_lookup_prime_cache(&owned).await;
                });
            }
            v
        }
        None => async_lookup(id).await,
    }
}

// ============================================================================
// 3. Asynchronous `#[concurrent_cached]`
//
// The sharded stores synchronize internally, so the static is the store itself
// behind a `OnceCell` (initialized by the first call) with no outer lock: reach
// through the cell and peek directly. The trait is `ConcurrentCacheExpiry`,
// which takes `&K` rather than a `Borrow<Q>`.
// ============================================================================

#[concurrent_cached(ttl_secs = 2, key = "String", convert = r#"{ id.to_string() }"#)]
async fn sharded_lookup(id: &str) -> String {
    let n = COMPUTES.fetch_add(1, Ordering::SeqCst) + 1;
    tokio::time::sleep(COMPUTE).await;
    format!("{id}-v{n}")
}

async fn sharded_lookup_refreshed(id: &str) -> String {
    // `get()` is `None` only before the first call has initialized the cell, which
    // is indistinguishable from a miss for our purposes.
    let peeked = SHARDED_LOOKUP
        .get()
        .map(|cache| cache.peek_expires_at(&id.to_string()));

    match peeked {
        Some((Some(v), expires_at)) => {
            if needs_refresh(expires_at) {
                let owned = id.to_string();
                tokio::spawn(async move {
                    sharded_lookup_prime_cache(&owned).await;
                });
            }
            v
        }
        _ => sharded_lookup(id).await,
    }
}

// ============================================================================
// 4. Collapsing concurrent refreshes
//
// Every caller that reads the entry between the threshold and the landing of the
// new value sees the same short remaining ttl, so each spawns its own refresh:
// N readers cause N recomputes. Track the keys already being refreshed and let
// the first caller win. `sync_writes = "by_key"` does NOT do this: its per-key
// lock covers the store write, not the function body (that is what keeps a
// refresh from blocking readers).
// ============================================================================

static REFRESHING: Mutex<Option<HashSet<String>>> = Mutex::new(None);

/// Returns `true` if this caller claimed the refresh for `key`.
fn claim_refresh(key: &str) -> bool {
    let mut guard = REFRESHING.lock().expect("refresh set poisoned");
    guard
        .get_or_insert_with(HashSet::new)
        .insert(key.to_string())
}

fn release_refresh(key: &str) {
    let mut guard = REFRESHING.lock().expect("refresh set poisoned");
    if let Some(set) = guard.as_mut() {
        set.remove(key);
    }
}

async fn async_lookup_refreshed_deduped(id: &str) -> String {
    let (value, expires_at) = {
        let cache = ASYNC_LOOKUP.read().await;
        cache.peek_expires_at(&id.to_string())
    };

    match value {
        Some(v) => {
            // `claim_refresh` runs only past the threshold, so the uncontended
            // path never touches the mutex.
            if needs_refresh(expires_at) && claim_refresh(id) {
                let owned = id.to_string();
                tokio::spawn(async move {
                    async_lookup_prime_cache(&owned).await;
                    // Release only after the new value is stored, so a caller that
                    // arrives mid-refresh sees the claim rather than starting a second.
                    release_refresh(&owned);
                });
            }
            v
        }
        None => async_lookup(id).await,
    }
}

// ============================================================================
// 5. Never expired, never blocked
//
// The property that separates this from stale-while-revalidate. Read one key
// across a window that spans the threshold and check three things: the value was
// replaced (so the refresh really ran), no read was served an entry past its
// deadline, and no read took anywhere near the recompute time.
// ============================================================================

/// Reads `id` every `step` for `window`, returning the distinct values observed in
/// order plus the slowest single read.
async fn poll(id: &str, window: Duration, step: Duration) -> (Vec<String>, Duration) {
    let until = Instant::now() + window;
    let mut observed: Vec<String> = Vec::new();
    let mut slowest = Duration::ZERO;

    while Instant::now() < until {
        let started = Instant::now();
        let value = async_lookup_refreshed_deduped(id).await;
        slowest = slowest.max(started.elapsed());
        if observed.last() != Some(&value) {
            observed.push(value);
        }
        tokio::time::sleep(step).await;
    }

    (observed, slowest)
}

#[tokio::main]
async fn main() {
    // --- 0. the policy ------------------------------------------------------
    // The `(Some(v), None)` case, which none of the ttl-backed reads below can
    // produce: an entry with no deadline never expires, so it never refreshes.
    println!("no deadline -> refresh: {}", needs_refresh(None));
    assert!(
        !needs_refresh(None),
        "an entry with no deadline must never be refreshed"
    );

    // --- 1. synchronous -----------------------------------------------------
    println!("\nsync `#[cached]`");
    let before = compute_count();
    let first = sync_lookup_refreshed("a");
    println!(
        "  cold miss  -> {first} ({} compute)",
        compute_count() - before
    );

    let early = sync_lookup_refreshed("a");
    println!(
        "  early read -> {early}, {}ms left, over the {}ms threshold, no refresh",
        sync_remaining("a").unwrap_or_default().as_millis(),
        THRESHOLD.as_millis()
    );
    assert_eq!(early, first);
    assert_eq!(
        compute_count() - before,
        1,
        "a read above the threshold must not refresh"
    );

    std::thread::sleep(Duration::from_millis(1_300));
    let started = Instant::now();
    let at_threshold = sync_lookup_refreshed("a");
    let remaining = sync_remaining("a").unwrap_or_default();
    println!(
        "  threshold  -> {at_threshold} returned in {}ms with {}ms still live, refresh spawned",
        started.elapsed().as_millis(),
        remaining.as_millis()
    );
    assert_eq!(at_threshold, first, "the entry is refreshed, not evicted");
    assert!(!remaining.is_zero(), "the entry must still be live");
    assert!(started.elapsed() < COMPUTE / 2, "the caller must not wait");

    std::thread::sleep(Duration::from_millis(400));
    let refreshed = sync_lookup_refreshed("a");
    println!(
        "  after bg   -> {refreshed} ({} computes), replaced before expiring",
        compute_count() - before
    );
    assert_ne!(refreshed, first, "the refresh must have replaced the value");
    assert_eq!(compute_count() - before, 2);

    // --- 2. asynchronous ----------------------------------------------------
    println!("\nasync `#[cached]`");
    let before = compute_count();
    let first = async_lookup_refreshed("b").await;
    println!("  cold miss  -> {first}");

    tokio::time::sleep(Duration::from_millis(1_300)).await;
    let started = Instant::now();
    let at_threshold = async_lookup_refreshed("b").await;
    println!(
        "  threshold  -> {at_threshold} returned in {}ms, refresh spawned",
        started.elapsed().as_millis()
    );
    assert_eq!(at_threshold, first);
    assert!(started.elapsed() < COMPUTE / 2, "the caller must not wait");

    tokio::time::sleep(Duration::from_millis(400)).await;
    let refreshed = async_lookup_refreshed("b").await;
    println!(
        "  after bg   -> {refreshed} ({} computes)",
        compute_count() - before
    );
    assert_ne!(refreshed, first);
    assert_eq!(compute_count() - before, 2);

    // --- 3. sharded ---------------------------------------------------------
    println!("\nasync `#[concurrent_cached]`");
    let before = compute_count();
    let first = sharded_lookup_refreshed("c").await;
    println!("  cold miss  -> {first}");

    tokio::time::sleep(Duration::from_millis(1_300)).await;
    let started = Instant::now();
    let at_threshold = sharded_lookup_refreshed("c").await;
    println!(
        "  threshold  -> {at_threshold} returned in {}ms, refresh spawned",
        started.elapsed().as_millis()
    );
    assert_eq!(at_threshold, first);
    assert!(started.elapsed() < COMPUTE / 2, "the caller must not wait");

    tokio::time::sleep(Duration::from_millis(400)).await;
    let refreshed = sharded_lookup_refreshed("c").await;
    println!(
        "  after bg   -> {refreshed} ({} computes)",
        compute_count() - before
    );
    assert_ne!(refreshed, first);
    assert_eq!(compute_count() - before, 2);

    // --- 4. deduplicated refresh --------------------------------------------
    println!("\ncollapsing concurrent refreshes");
    let cold = async_lookup_refreshed_deduped("e").await;
    tokio::time::sleep(Duration::from_millis(1_300)).await;

    let before = compute_count();
    let started = Instant::now();
    let mut handles = Vec::new();
    for _ in 0..8 {
        handles.push(tokio::spawn(async {
            async_lookup_refreshed_deduped("e").await
        }));
    }
    let mut served = Vec::new();
    for handle in handles {
        served.push(handle.await.expect("reader task panicked"));
    }
    let elapsed = started.elapsed();
    println!(
        "  8 concurrent readers past the threshold -> served {} in {}ms",
        served[0],
        elapsed.as_millis()
    );
    assert!(
        served.iter().all(|v| *v == cold),
        "all readers see the live value"
    );
    assert!(elapsed < COMPUTE / 2, "no reader may wait for the refresh");

    tokio::time::sleep(Duration::from_millis(400)).await;
    let refreshes = compute_count() - before;
    println!(
        "  -> {refreshes} recompute(s), next read {}",
        async_lookup_refreshed_deduped("e").await
    );
    assert_eq!(
        refreshes, 1,
        "the in-flight guard must collapse the refreshes to one"
    );

    // --- 5. never expired, never blocked ------------------------------------
    println!("\nnever expired, never blocked");
    let before = compute_count();
    let expired_before = expired_reads();
    let first = async_lookup_refreshed_deduped("f").await;

    // 1.6s of reads over a 2s ttl: the threshold trips at 1.0s and the refresh
    // lands ~0.2s later, so the window covers the handover in both directions.
    let (observed, slowest) = poll(
        "f",
        Duration::from_millis(1_600),
        Duration::from_millis(100),
    )
    .await;
    println!("  reads across the threshold -> {observed:?}");
    println!(
        "  slowest read {}ms, recompute {}ms, {} expired read(s)",
        slowest.as_millis(),
        COMPUTE.as_millis(),
        expired_reads() - expired_before
    );
    assert_eq!(observed.len(), 2, "the value must be replaced mid-window");
    assert_eq!(
        observed[0], first,
        "reads before the handover see the old value"
    );
    assert_ne!(observed[1], first, "reads after it see the refreshed value");
    assert_eq!(
        compute_count() - before,
        2,
        "one cold compute plus exactly one background refresh"
    );
    assert!(
        slowest < COMPUTE / 2,
        "no read may wait for the recompute (slowest {slowest:?})"
    );

    // The point of issue #91: the entry was replaced without any caller ever
    // reaching the expired state that stale-while-revalidate exists to absorb.
    assert_eq!(
        expired_reads(),
        0,
        "no read in this example may observe an expired entry"
    );

    println!("\nrefresh-before-expiry ok");
}
